# print("Assalom alaykum!")
# print('Hi guys')
print('lorem ipsum')
print('Men "Lenovo" markasidagi kompyuter ishlataman.')
print("Men \"Lenovo\" markasidagi kompyuter ishlataman.")
print("Men 'iPhone' markasidagi telefon ishlataman")
print('Men \'iPhone\' markasidagi telefon ishlataman')
print("Odami ersang, demagil odami, \nOniki, yo'q xalq g'amidin g'ami")
# Arifmetik amallar
print(5 + 6)
print(10 - 4)
print(12 * 3)
print(15 / 5, 12 * 5, 52 + 17, 65 - 15)
print(15 // 7)
print(65 // 5)
print(5 ** 4, 12 ** 2)
print(64 ** (1 / 2))
print(625 ** (1 / 4))
print(12 % 5)
print(4 % 7) # 4
print(5 % 6) # 5
print("Beshning kvadrati", 5 ** 2, "ga teng")
print('3x3=',3*3)
# Amaliyot
print("\"Nexia\", \"Tico\", 'Damas' ko'rganlar qilar havas")
print('"Nexia", "Tico", \'Damas\' ko\'rganlar qilar havas')
print("5-ning 4-darajasi" ,5 ** 4)
print("22 ni 4 ga bo'lganda qoldiq", 22 % 4)
print("Tomonlari 125 ga teng kvadratning yuzi", 125 ** 2, "va perimetri", 125 * 4)
print("Doiraning diametri 12 ga teng radiusi", 12 / 2, "kvadrati", (6 ** 2) * 3.14)
print("Tomonlari 3, 4, 5 ga teng bo'lgan uchburchakning yuzasi", (6 * (6 - 3) * (6 - 4) * (6 - 5)) ** (1 / 2), "ga teng")